org: wild0kl
app: coinbase-dca
service: coinbase-dca
configValidationMode: error

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2 # oregon
  memorySize: 128
  timeout: 30
  lambdaHashingVersion: 20201221
  environment:
    # common
    CBP_KEY: ${env:CBP_KEY}
    CBP_SECRET: ${env:CBP_SECRET}
    CBP_PASSPHRASE: ${env:CBP_PASSPHRASE}
    # buy
    CBP_USD_ACCOUNT: ${env:CBP_USD_ACCOUNT}
    BUY_BTC_AMOUNT: ${env:BUY_BTC_AMOUNT}
    # deposit
    CBP_PAYMENT_METHOD: ${env:CBP_PAYMENT_METHOD}
    DEPOSIT_USD_AMOUNT: ${env:DEPOSIT_USD_AMOUNT}

functions:
  get:
    handler: handler.get
  buy:
    handler: handler.buy
    events:
      - schedule:
          enabled: true
          rate: "cron(23 3 * * ? *)" # this time is in UTC
  deposit:
    handler: handler.deposit
    events:
      - schedule:
          enabled: true
          rate: "cron(0 12 1 * ? *)" # ~8am on the first day of the month
