org: wild0kl
app: coinbase-dca
service: coinbase-dca
configValidationMode: error

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2 # oregon
  memorySize: 128
  timeout: 30
  lambdaHashingVersion: 20201221
  environment:
    # common
    CBP_KEY: ${env:CBP_KEY}
    CBP_SECRET: ${env:CBP_SECRET}
    CBP_PASSPHRASE: ${env:CBP_PASSPHRASE}
    # buy
    CBP_USD_ACCOUNT: ${env:CBP_USD_ACCOUNT}
    BUY_BTC_AMOUNT: ${env:BUY_BTC_AMOUNT}

functions:
  get:
    handler: handler.get
  buy:
    handler: handler.buy
    events:
      - schedule:
          enabled: true
          rate: "cron(23 23 * * ? *)" # 11:23pm every day
  deposit:
    handler: handler.deposit
    events:
      - schedule:
          enabled: false
          rate: "cron(8 7 1,15 * ? *)" # 1st and 15th of every month at 7:08am
